# Generated by Django 4.2.16 on 2024-09-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaborateRequest',
        ),
    ]
