# Generated by Django 4.2.16 on 2024-10-08 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_sharedrecipecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrecipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
