# Generated by Django 4.2.16 on 2024-10-09 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_alter_sharedrecipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrecipe',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
